### ISSUE TITLE
Error 500 on live site - But works on Test site

### ISSUE THREAD

**Issue by neeesn** [praxisdigital/moodle-local_userenrols#2]
The plugin is the "newest" version and it seems to be working on the test site but on the live site it shows 500 error - I have made a small video showing the error and how to get to the plugin: https://www.loom.com/share/538d3471b78b41068d62093cf8560126

Hubspot: https://app-eu1.hubspot.com/contacts/25645903/ticket/1338167482

**Comment by frederikmillingpytlick** [comment]
I've not done anything yet, but it seems to work now?


https://moodle.ruc.dk/local/userenrols/import.php?id=13479
![Image](https://github.com/praxisdigital/moodle-local_userenrols/assets/78727001/5bab6b2b-c398-4480-815f-84923919e816)

**Comment by neeesn** [comment]
Jeg får stadig en fejl 500:
https://www.loom.com/share/d829f3368fd94b23a1a79f04ad9a0e75

**Comment by neeesn** [comment]
![Image](https://github.com/praxisdigital/moodle-local_userenrols/assets/1931926/ca6effb7-bf40-4420-af9a-1bd30d238eed)

**Comment by frederikmillingpytlick** [comment]
I still don't get the error, but we've concluded that updating the plugin to the newest version should fix the issue.
